version: '3.8'
services:
  titik-nol-webservice:
    build: .
    container_name: titiknol_api
    ports:
      - "8003:80"
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    command: >
      bash -c "
      composer install &&
      chown -R www-data:www-data /var/www/html/writable &&
      chmod -R 775 /var/www/html/writable &&
      apache2-foreground
      "
    restart: always
    networks:
      - apps-networks
networks:
  apps-networks:
    external: true